aggr_export_path: str()
projects: list(include('project'))
---
project:
  name: str()
  provider: str()
  apikey: str()
  plants: list(include('plant'))

plant:
  name: str()
  username: str()
  start: day()
  size: num()
  compensation: num()
